context:
  name: cc_torch
  version: "0.1.0"
  source_repo: "ronghanghu/cc_torch"
  commit: "446e9360ed10d3c8d03925ccb5f220ccb62009de"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  git: https://github.com/${{ source_repo }}.git
  rev: ${{ commit }}
  depth: 1

build:
  number: 0
  string: cuda${{ cuda_compiler_version | replace('.', '') }}_torch${{ pytorch | replace('.', '') }}_py${{ CONDA_PY }}_${{ PKG_BUILDNUM }}
  script:
    content:
      - pip install torch==${{ pytorch }} --index-url https://download.pytorch.org/whl/cu${{ cuda_compiler_version | replace('.', '') }}
      - ${{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
    env:
      FORCE_CUDA: "1"
      - if: ${{ cuda_compiler_version == "12.4" and linux }}
        then:
          TORCH_CUDA_ARCH_LIST: "5.0;6.0;7.0;8.0;9.0+PTX"
      - if: ${{ cuda_compiler_version == "12.4" and win }}
        then:
          TORCH_CUDA_ARCH_LIST: "7.0;8.0;9.0+PTX"
      - if: ${{ cuda_compiler_version == "12.6" }}
        then:
          TORCH_CUDA_ARCH_LIST: "7.0;8.0;9.0+PTX"
      - if: ${{ cuda_compiler_version == "12.8" or cuda_compiler_version == "12.9" }}
        then:
          TORCH_CUDA_ARCH_LIST: "7.0;8.0;9.0;10.0;12.0+PTX"
      - if: ${{ cuda_compiler_version == "13.0" }}
        then:
          TORCH_CUDA_ARCH_LIST: "8.0;9.0;10.0;12.0+PTX"
  missing_dso_whitelist:
    - "*/libc10*"
    - "*/libtorch*"
    - "*/libtorch_cpu*"
    - "*/libtorch_cuda*"
    - "*/libtorch_python*"

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('cuda') }}
    - ${{ stdlib('c') }}
  host:
    - python
    - pip
    - setuptools
    - cuda-version ${{ cuda_compiler_version }}
  run:
    - python
    - pytorch >=${{ pytorch }}
    - __cuda
    - cuda-cudart
  run_constrained:
    - cuda-version >=${{ cuda_compiler_version }}

tests:
  - python:
      imports:
        - cc_torch

about:
  homepage: https://github.com/ronghanghu/cc_torch
  license: MIT
  summary: Connected Components for PyTorch (CUDA)
